name: Build pdfs & anki decks

on:
  pull_request:
  push:

jobs:
  build_all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          echo '###### PDFS ######'
          nix run '.#compile-all'
          echo '###### ANKI ######'
          nix run '.#genanki'
      - name: push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: auto-update pdfs & anki decks
