name: Build unnecessary github pages

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: build
        run: nix run '.#build-web'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
